enable_color: true
enable_depth: true
enable_infra1: false
enable_infra2: false
enable_gyro: false
enable_accel: false
depth_module.depth_profile: "424x240x6"
rgb_camera.color_profile: "640x480x15"
align_depth.enable: true
publish_tf: true
tf_publish_rate: 0.0
base_frame_id: "realsense_camera_link"
clip_distance: 5.0
pointcloud__neon_.enable: true
pointcloud__neon_.allow_no_texture_points: true
wait_for_device_timeout: -1.0
reconnect_timeout: -1.0
depth_module.enable_auto_exposure: true
rgb_camera.enable_auto_exposure: true
